#!/usr/local/bin/busybox sh
# SPDX-License-Identifier: MIT
set -eu
BB=/usr/local/bin/busybox
state=/run/liuqin-usb-rescue
mkdir -p "$state"

case ${1:-start} in
start)
	[ -e /sys/class/net/usb0 ] || exit 0
	$BB ip link set usb0 up
	$BB ip address add 192.168.7.2/24 dev usb0 2>/dev/null || :
	cat >"$state/udhcpd.conf" <<'EOF'
start 192.168.7.10
end 192.168.7.19
interface usb0
lease_file /run/liuqin-usb-rescue/leases
pidfile /run/liuqin-usb-rescue/udhcpd.pid
max_leases 10
option subnet 255.255.255.0
EOF
	: >"$state/leases"
	$BB udhcpd "$state/udhcpd.conf"
	$BB telnetd -b 192.168.7.2:2323 -l /usr/local/bin/liuqin-shell
	;;
stop)
	$BB killall telnetd udhcpd 2>/dev/null || :
	;;
*) exit 2 ;;
esac
